version: '3.8'

services:
  php-apache:
    build: .
    container_name: php_apache_container
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - php-apache
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
