# Use an official Nginx image as the base
FROM nginx:latest

# Copy custom Nginx config
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
